// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oblig1.DAL;

#nullable disable

namespace Oblig1.Migrations
{
    [DbContext(typeof(ItemDbContext))]
    [Migration("20230919093034_eierDbSet")]
    partial class eierDbSet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("Oblig1.Models.Hus", b =>
                {
                    b.Property<int>("husId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Addresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Beskrivelse")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Pris")
                        .HasColumnType("TEXT");

                    b.Property<double>("areal")
                        .HasColumnType("REAL");

                    b.Property<string>("by")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("eierID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("erTilgjengelig")
                        .HasColumnType("INTEGER");

                    b.Property<int>("romAntall")
                        .HasColumnType("INTEGER");

                    b.HasKey("husId");

                    b.HasIndex("eierID");

                    b.ToTable("hus");
                });

            modelBuilder.Entity("Oblig1.Models.Ordre", b =>
                {
                    b.Property<int>("ordreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Dato")
                        .HasColumnType("TEXT");

                    b.Property<string>("betaltGjennom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("husID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("kundeID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ordreId");

                    b.HasIndex("husID");

                    b.HasIndex("kundeID");

                    b.ToTable("ordre");
                });

            modelBuilder.Entity("Oblig1.Models.Person", b =>
                {
                    b.Property<int>("personID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Addresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fodselsdato")
                        .HasColumnType("TEXT");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TelefonNmr")
                        .HasColumnType("INTEGER");

                    b.HasKey("personID");

                    b.ToTable("person");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Person");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Oblig1.Models.Bruker", b =>
                {
                    b.HasBaseType("Oblig1.Models.Person");

                    b.Property<string>("Passord")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("erAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("erEier")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Bruker");
                });

            modelBuilder.Entity("Oblig1.Models.Kunde", b =>
                {
                    b.HasBaseType("Oblig1.Models.Person");

                    b.Property<int>("kundeId")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Kunde");
                });

            modelBuilder.Entity("Oblig1.Models.Eier", b =>
                {
                    b.HasBaseType("Oblig1.Models.Bruker");

                    b.Property<int>("eierID")
                        .HasColumnType("INTEGER");

                    b.Property<long>("kontoNummer")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Eier");
                });

            modelBuilder.Entity("Oblig1.Models.Hus", b =>
                {
                    b.HasOne("Oblig1.Models.Eier", "Eier")
                        .WithMany()
                        .HasForeignKey("eierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eier");
                });

            modelBuilder.Entity("Oblig1.Models.Ordre", b =>
                {
                    b.HasOne("Oblig1.Models.Hus", "hus")
                        .WithMany()
                        .HasForeignKey("husID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oblig1.Models.Kunde", "kunde")
                        .WithMany("ordreListe")
                        .HasForeignKey("kundeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("hus");

                    b.Navigation("kunde");
                });

            modelBuilder.Entity("Oblig1.Models.Bruker", b =>
                {
                    b.HasOne("Oblig1.Models.Person", "person")
                        .WithMany()
                        .HasForeignKey("personID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("person");
                });

            modelBuilder.Entity("Oblig1.Models.Eier", b =>
                {
                    b.HasOne("Oblig1.Models.Bruker", "bruker")
                        .WithMany()
                        .HasForeignKey("personID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bruker");
                });

            modelBuilder.Entity("Oblig1.Models.Kunde", b =>
                {
                    b.Navigation("ordreListe");
                });
#pragma warning restore 612, 618
        }
    }
}
